Unroot all the things
underground-software/singularity pull request #81
Opened 2024-04-03 18:42 UTC by charliemirabile

Its official, we have gone fully rootless. (technically the master process of nginx spawns as root and only the workers drop their privs and run as nginx:nginx, but it is good to keep it this way because the alternative makes the bind mount for socks more tricky)

2024-04-03 20:59 UTC, theyoyojo requested changes
Tests fail as follows:

```
...
Traceback (most recent call last):
  File "/orbit/hyperspace.py", line 203, in <module>
    hyperspace_main(sys.argv[1:])
  File "/orbit/hyperspace.py", line 197, in hyperspace_main
    args.do(args)
  File "/orbit/hyperspace.py", line 121, in do_newuser
    db.usr_ins((args.username, do_bcrypt_hash(args, get=True),
  File "/orbit/db.py", line 98, in usr_ins
    def usr_ins(usr): return _set(USR_INS, usr)
                             ^^^^^^^^^^^^^^^^^^
  File "/orbit/db.py", line 31, in _set
    def _set(cmd, reps=()): return _do(cmd, reps, set_=True, get_=True)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/orbit/db.py", line 17, in _do
    ret = new.execute(cmd, reps)
          ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: attempt to write a readonly database
...
```

Something funky going on with the blob?

2024-04-03 21:53 UTC, charliemirabile commented
perhaps you need to purge your volumes? The tests pass for me

2024-04-04 01:19 UTC, theyoyojo approved these changes

2024-04-04 01:19 UTC, theyoyojo commented
after purging volumes, tests now pass

2024-04-04 01:19 UTC, merged